### ISSUE TITLE
Deploy app

### ISSUE THREAD

**Issue by jorcox** [MarcosCM/NASA-SpaceApps2016-TimeFlies#16]

**Comment by Shathe** [comment]
Antes habría que desplegarla y dejarla aprendiendo un día

**Comment by jorcox** [comment]
Si

**Comment by jorcox** [comment]
Marcos prepara la máquina y lo desplegamos hoy para que aprenda hasta mañana como mínimo.

**Comment by mcanalesmayo** [comment]
App deployed: http://52.28.76.182:8080/
